### ISSUE TITLE
ENH: Subscription screen

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/upper-room#16]
## Description

A view for managing the user's subscription.

## Completion Conditions

- [ ] The user can subscribe to the app
- [ ] The user can manage their subscription
- [ ] The screen links to appropriate resources for managing their payment methods

## Tasks

- [ ] ENH: Add a testing StoreKit configuration
- [ ] Add next steps...
