### ISSUE TITLE
EXT: Create a repo for the Android version

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/upper-room#17]
## Tasks

- [ ] Create an organization to group the repositories
- [ ] Transfer this repo to the organization
- [ ] Create a repository for the Android version in the new organization

**Comment by Jython1415** [comment]
GitHubの「organization」を有料であるため、使わないことにしました。
