### ISSUE TITLE
CLN: Review the entire codebase and look for places for improvement

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/upper-room#19]
## Tasks

- [ ] List all files to review (add as tasks below)

**Comment by Jython1415** [comment]
## ファイル

- [ ] Upper_Room_JapanApp
- [ ] ContentView
- [ ] MainTabView
- [ ] DevotionListView
- [ ] DevotionView
- [ ] DeveloperView
- [ ] PDFDocumentView
- [ ] SettingsView
- [ ] SplashScreenView
- [ ] DevotionManager
- [ ] PublicationManager
- [ ] ContentManager
- [ ] ContentFileParser
- [ ] DownloadManager
- [ ] DevotionDataParser
- [ ] NotificationManager
- [ ] DebugManager
- [ ] ReleaseManager
- [ ] Model
- [ ] ColorExtension
- [ ] Persistence

**Comment by Jython1415** [comment]
### Upper_Room_JapanApp

- [ ] Swift用のLinter: [SwiftLint](https://github.com/realm/SwiftLint)

**Comment by Jython1415** [comment]
- [ ] `Launch Screen`のセットアップができたので、`SplashScreenView`はアプリアイコンを含めた画面にするのがいいだろう
