### ISSUE TITLE
Add issues to reflect development priorities

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/upper-room#2]
## Description

The development process was previously tracked in a series of google documents. The contents of these google documents should be transferred to this repository as a series of issues.

## Tasks

- [x] Identify all sources of development progress
- [x] Transfer tasks as issues (mark tasks or issues that require clarification)

**Comment by Jython1415** [comment]
## Sources of development progress

- [ ] Progress reports
  - [ ] 11/08/2022
  - [ ] 11/13/2022
  - [ ] 11/29/2022
  - [ ] 12/16/2022
  - [ ] 01/22/2023
  - [ ] [WIP] Progress Report
- [ ] Notion dashboard
