### ISSUE TITLE
ENH: Use an image for the Splash Screen

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/upper-room#24]
## Description

Set it so that the image is downloaded from a remote source and is cached for later use. On the first load, use whatever image is cached (or maybe a dark blue background).

## Tasks

- [ ] Use an image for the Splash Screen
- [ ] Load an image for the Splash Screen
- [ ] Cache the image
- [ ] Implement sensible default behavior
- [ ] TST: Add tests for the Splash Screen behavior
