### ISSUE TITLE
TST: 現在のビルドを手動でテストする

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/upper-room#7]
## Problem

It has been a while since I have worked on this project and I am not sure if anything is broken.

## Solution

Go through each feature and test to see if it works as expected.

## Tasks

- [x] Look through the code and list *all* features to test
- [x] Note any problems
- [x] Create issues for them

**Comment by Jython1415** [comment]
## Features to check

- [ ] Content manager downloading info
- [ ] Debug manager to turn logging on and off
- [ ] Bookmarking devotions
- [ ] Images for devotions
- [ ] Devotion display
- [ ] Notifications for devotions
- [ ] Publication list
- [ ] PDF viewing
- [ ] Release management with ReleaseManager
- [ ] Test all Developer View features
- [ ] Switching between tabs on the main view
- [ ] Check the functionality of all settings in the Settings view
- [ ] Does the Splash Screen display properly?

**Comment by Jython1415** [comment]
> * [ ]  Notifications for devotions

この機能をテストするのは現在難しいので、別のイシューでテストします。

- #45

**Comment by Jython1415** [comment]
作成したイシュー

- #46 
- #47 
- #48 
- #49 
- #50 
- #51 
- #52 
- #53 
- #54 
- #55 
- #56 
- #57 
- #58 
- #59
